# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f187a7ecd2be27708f2b3ee6bed6a7efba98595cf003514574122c17c9730be9a70df9e4121a70060ecdbf4efd91094d0a5a816e2ecc80f6450c4301b49beb38

test:
  secret_key_base: 794d12b0ff0c5fe8534de3e2ebd760dec9bc248d0901b10015ebc8eec8eda8b6940a2ccb5f524a4c114b6b6813d6b8dc3be44135449c3228482a4dd5bd98dd10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
